manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: gpeye
      url-base: https://github.com/GPeye
    - name: tokyo2006
      url-base: https://github.com/tokyo2006
    - name: englmaxi
      url-base: https://github.com/englmaxi
    - name: gpeye
      url-base: https://github.com/GPeye
    - name: xvargr
      url-base: https://github.com/xvargr
  projects:
    # - name: mario-peripheral-animation
    #   remote: gpeye
    #   revision: main
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0
      import: app/west.yml
    - name: prospector-zmk-module
      remote: tokyo2006
      revision: micro_spi2  
    - name: zmk-dongle-display
      remote: englmaxi
      revision: v0.3
    # - name: hammerbeam-slideshow
    #   remote: gpeye
    #   revision: main
    # - name: urchin-peripheral-animation
    #   remote: gpeye
    #   revision: main
    - name: nice-vibes
      remote: xvargr
      revision: main
  self:
    path: config
